// fourthwall-catalog.js
// Authoritative catalog of the 16 real Tall Boy storefront products
// (shop.tallboy.us). Titles, prices and CDN image URLs were pulled live
// from the public Fourthwall storefront (Product JSON-LD). This acts as the
// seed + fallback whenever a live re-scrape is unavailable.
//
// Shop ID: sh_fb9f724b-ee84-4b09-954a-fd2966f8ca8c

const TALL_BOY_PRODUCTS = [
  { slug: 'ships-sink-t-shirt', title: 'Ships Sink T-Shirt', price: '$22.95', image_url: 'https://imgproxy.fourthwall.dev/HmRjwwJd151uvj2u3NClYZhNnoPWkfxDiLdq7ZEaIG8/w:1920/sm:1/enc/hzUE8te2znPz_mWh/aUAR0SE3wJvtWqA4/HINidxMkKyTrRKpp/O4dbubU0Y08E8Apa/Eq8W3OlxHgXCvHE2/gMwGmPVmE69fhQHF/JS8x05ymRBtGbgQx/k7m3t3yH_J3STeed/pR6-ygIEvp8BvGm_/TKUrzL_MPbMzzGTu/zvAuHZ1R59IVHW1l/YJ0uzseJfL690niH/7Kh6ZWEwkLIT6C_w/IiSZfA.webp', checkout_url: 'https://shop.tallboy.us/products/ships-sink-t-shirt' },
  { slug: 'take-an-inventory-of-your-life-womens-t-shirt', title: "Take An Inventory Of Your Life Women's T-Shirt", price: '$21.95', image_url: 'https://imgproxy.fourthwall.dev/ZS8mdT3scdTk0PI9ddT5t1gqBpUJR5hHbufTL9yx06A/w:1920/sm:1/enc/0B2RIU4EOcjhFS-E/OdSfOGWvsRc2kNJ4/Icxm5loOuqZF6TGK/CgUmgxzTWDA24V_1/2hz0BOzHf_TRGsBC/1K6UDIhK8c1HZdEU/16zgGZCD48bpC7O6/x8r-Hb24IvJsRXcz/5s5jCZe5O_t9Yx5u/4Kb6dkfoOSDF8gaY/dwPMLlshf_saGecS/U9GK9DIlkTLBEG8g/pyE-E6Wk4qjUM6WY/b65IbQ.webp', checkout_url: 'https://shop.tallboy.us/products/take-an-inventory-of-your-life-womens-t-shirt' },
  { slug: 'take-an-inventory-of-your-life-t-shirt', title: 'Take An Inventory Of Your Life T-Shirt', price: '$22.95', image_url: 'https://imgproxy.fourthwall.dev/FdZMMzNOTmE_6upIRNmS9O_Z1zWup1ONGt25qAYYtgk/w:1920/sm:1/enc/klM7o-Sej_YU124Z/7eo-REXRTH8gtlOK/T8zv1TOgu7ULThDU/EeCJZVYSrHAK_UXm/_mPSPuOHdqjWtIum/nDOfUCyVShjf1U-y/2gP90a6qQVgee4Hi/hNIT7STO6vuVZbK2/PrIfxCGFp3V6CGqY/3Y_uZwpr9uubsja2/b3kcplnBC0mr96oG/qGg2-iDGds4MMkGr/C8xNSpny26puoDVH/Hf58Ow.webp', checkout_url: 'https://shop.tallboy.us/products/take-an-inventory-of-your-life-t-shirt' },
  { slug: 'tbj-large-tote-bag-w-pocket', title: 'TBJ Large Tote Bag w/ Pocket', price: '$35.00', image_url: 'https://imgproxy.fourthwall.dev/XVoYJyDzdc5H2_fC7WyRJT9TNxkNtwtpymiYf2av88g/w:1920/sm:1/enc/R6AN-BhLkgwt6-Tx/fRcWPrVDtRiEIHuZ/5US2O1hj_TOMY2OO/-Z4odO736-Ike_6W/ny0IOYqbCWaAcWNi/CZBv7GacCmMsRnLF/kbSBiw1gELUZ7mBa/Q5U19JLTb0zoS-RT/5auWruM8xHY6xHg-/HgBKD-c0xlyTRDcJ/9YdfDNatVMzb-PiB/4NDeurYVxX85QHOX/zpz8_52GV3oBSfRM/-So_mg.webp', checkout_url: 'https://shop.tallboy.us/products/tbj-large-tote-bag-w-pocket' },
  { slug: 'trucker-tank-top', title: 'Trucker Tank Top', price: '$24.95', image_url: 'https://imgproxy.fourthwall.dev/ufNNGiWwm34upRWfxIDrhHM9f1J75yYC41om98vk0jw/w:1920/sm:1/enc/EFXNc3EZUnmORivD/ZmZ4SmqtYq-6h8Op/-Gy093o3p8jC-Aox/KEsWGn_Tn-aqWsJt/IpBSAvBcd4CHYjjV/cPS5fiH8RS__tCra/WzFSqjxqzT5gj_3t/5fuxbNIPfkqVZ8Ci/R7q2UgXQIhGR-WF-/OX9gqIylnhwtGOs0/xLSZA7p799WsHWcQ/R6W6182LLdZcCqIa/-RStHoFoJQh2Nt1x/_K3kLQ.webp', checkout_url: 'https://shop.tallboy.us/products/trucker-tank-top' },
  { slug: 'word-of-the-day-ungainly-t-shirt', title: 'Word of the Day: Ungainly T-Shirt', price: '$25.95', image_url: 'https://imgproxy.fourthwall.dev/gWfrd05CP0SO8zFOJFmbc_WoSyFh0Zs1kTZ9j7AzJks/w:1920/sm:1/enc/6n1stiG-NNepboY-/pmrELP_1L6BQxj3b/0e5KxVs_gTXN4Xi6/x1oAJvveRkLv5lS3/w8pnziCYe36CVt8o/S12ohvvw36Eu0qSH/hZn88UiE7dUXvd3A/qzlVVniXv5KeLpKg/3ase6FGp-Ed9YgDW/27OZvggqQFs92nEh/WaFOosKId1xPbQXo/qCiOBOABnUJoW-6U/fmtCu1mW-dOQWFE0/vSGd2VLdVPA2zBUF/dipbKWb_hEs.jpg', checkout_url: 'https://shop.tallboy.us/products/word-of-the-day-ungainly-t-shirt' },
  { slug: 'honk-da-horn', title: "Honk Da' Horn", price: '$27.95', image_url: 'https://imgproxy.fourthwall.dev/VPU9CzxUuvl06Yx7fL0bzDTfrRl_iHdv-PJPIWPwcb8/w:1920/sm:1/enc/WOljtbZKQ8vSJZT7/Y9a_gV-u45lTcA-R/DB4y0k4mv6W1Mkus/6VzuYwN5W8wjjUjD/sQTGAP4ogJj6MP5x/Ntyi3rWESd1H0C2x/gsoBqN5mCCVnx3m0/lBU0DTxnfJP9IwGk/QS9imun4tP6yRO7o/AZlNI03BflYLLXqi/RjT1eqEz2HB0vG3D/wnq4zziIUXG97AkX/SgeRJL38kpx-k-VI/zVL5dA.webp', checkout_url: 'https://shop.tallboy.us/products/honk-da-horn' },
  { slug: 'dont-forget-to-honk-the-horn-mug', title: "Don't Forget To Honk The Horn Mug", price: '$15.00', image_url: 'https://imgproxy.fourthwall.dev/rGS0HzS4sHWg8bQW78TQPmHWdUoHWnfrp0TDDxN6eJE/w:1920/sm:1/enc/sVhd3pY7bTwNapGx/X068rQlgTVt5xLke/sC0R4vx82YT8kfYU/Y8ZQrFf_FbPeqxPF/Nzw502q-piVWp1Vg/a1xK2Z1vxlrqGe_x/ektOwEaGcL-w36b0/KJRfqF7d0UJ9-3MH/y2kD154Q1kEDN7G_/Ec6ACTsdLkpqxJRq/3DBkxB8xZMH0qikj/Jt6b_gMVD8jsC_mE/0iBkUWFELDVBehPv/5Rm8jw.webp', checkout_url: 'https://shop.tallboy.us/products/dont-forget-to-honk-the-horn-mug' },
  { slug: 'tbj-what-we-drinkin-2', title: 'TBJ What We Drinkin', price: '$21.00', image_url: 'https://imgproxy.fourthwall.dev/3TkumGeTu7txE2at4ZdABi70Xmni2lhHTmE_aYRhe60/w:1920/sm:1/enc/y2zhBCS5exCO5ZVv/Nc2HlROVMMPINz4V/o7GfCFuNJ4EDoT7I/P2cz01WZEZ263Wyw/d8dA5GBQt7JhEeG5/sNvwE_oChjnGnoo4/YYj5Oe1UecWmKcHk/9blCC8sOT6c2Wi5t/xBNCwiH9IXWy83Ma/Wtv8QFtq03v6Dt4i/cUs6sMuVCqhpxJpu/Pz7gPcj7m9erEsXR/ExishL2Yjl6ds77b/qQ36ZA.webp', checkout_url: 'https://shop.tallboy.us/products/tbj-what-we-drinkin-2' },
  { slug: 'tbj-adult-beverage-glass-2', title: 'TBJ Adult Beverage Glass', price: '$21.00', image_url: 'https://imgproxy.fourthwall.dev/aVOVDRp6CGKfWPOVOtLe_Bc6hVwfYjIpvs3sCxvxN6k/w:1920/sm:1/enc/WOjQFF0QmYWJpNn-/va0CKQAQmNgSNcV1/AXqh-3BV0qo-Qbrn/uYAVBdIV6fXrSf8J/4eAKxDuIsoGlrTDW/EwqUgVnIg6GL1cqI/_CFaK4X8o-baw0_R/zdbNBXqZ7fBPsUoW/A0psRePhTMyk-F2C/ZPezSn1pZoyloDwm/ScVuGu42ZC_nQ2H1/M5WDIUELiYiOHhNN/w0K50HKxRiI_Poau/hzM1QKNC5q7dHHNy/wsOsTVEBOfo.jpg', checkout_url: 'https://shop.tallboy.us/products/tbj-adult-beverage-glass-2' },
  { slug: 'tbj-in-the-building-2', title: 'TBJ In The Building', price: '$28.00', image_url: 'https://imgproxy.fourthwall.dev/xCeGUrokOE1CB9Bymo56y0FpQi3scs3H_axomBxk0FQ/w:1920/sm:1/enc/igFOiNegpwRipKv2/1PAsy66IsKzYQcl2/13KXuh1iKBEXSz2i/pE2lj-g7nugOAJaP/cwXGtgVipUB-Jh2s/UqnadfvShOym93al/6wgI7Dpqqjx5C_DZ/5oRP4eQlNp4PFC3H/N4hxqUawZBrogSOo/-1NjKma3HA0dp0k8/OPn0jO5kywtcrcN6/avG-BRRM2h-NmeSm/Dm6rxG_ZFemfcZUr/Dg1iQUEEXeoLEzRt/sWpgl03-Z6E.jpg', checkout_url: 'https://shop.tallboy.us/products/tbj-in-the-building-2' },
  { slug: 'tbj-ladies-crop-tee', title: 'TBJ Ladies Crop Tee', price: '$30.00', image_url: 'https://imgproxy.fourthwall.dev/wFbelx1HtqgXTyc_KvvyGMuvgBOAgsMXBNgOlGA3Vq4/w:1920/sm:1/enc/HAPoQP5ML_gxu-To/Udm47D6Lnt5l5ASY/BYuR2ltHEjdUeea5/hTC9mU47vPdM419R/mDJAOKQuLIRtwmbl/jD4FAbZmsOGVzaWJ/bFnqnzyiU0PVME3s/89O5I1XPV8ygaaoL/ESXZO6uKmsMTk4v_/6kJVfaGUdarH36Ad/dCz_eMANpvavh8_r/A8JqsaJ9G2AnIGp4/wFg09YGwhKHW0KmD/Lc1ZmuDHDVjo5-sO/4li_QRNlk08.jpg', checkout_url: 'https://shop.tallboy.us/products/tbj-ladies-crop-tee' },
  { slug: 'tbj-in-the-building-mouse-pad-2', title: 'TBJ In The Building Mouse Pad', price: '$23.00', image_url: 'https://imgproxy.fourthwall.dev/SKWxxHHWx-1kzkaXg9Wv3ktApQWjoZlKzAKCDl19cO0/w:1920/sm:1/enc/tgThxAM_jOdq44iF/MqttAGzuokw88sui/eGh_gUwyQwknNaOA/GifrJfgYm5CeLCjw/J8lTfg2PUojTV8gX/mMpUQbbH381qP4f3/50f5TWv7iyLhQMDC/HuJud_dkRGaM_9M6/yq-jLqcWXzRUVaus/8AR66cMbaW6Tmo5n/UV7m32aPu0AcsRrY/fvh96-k5Y8X1CZ8w/vfIelUppF4ZeQpLn/MB6L_C1MLOCCsD4c/OsgTTBqhmrA.jpg', checkout_url: 'https://shop.tallboy.us/products/tbj-in-the-building-mouse-pad-2' },
  { slug: 'tbj-journal-2', title: 'TBJ Journal', price: '$23.00', image_url: 'https://imgproxy.fourthwall.dev/UQelV_WZEUyf-pH0ATJBxqHwx_uuEjBGgaL0WIBCTOA/w:1920/sm:1/enc/HY4gaUEKxU-LgP_W/hOQ59RKXYOqaWszX/Qh7KJJRQzhKGNjom/0x-LQnTjuAtt-2u6/mFc8r2uWoCKbGTYT/sjuRIR4g9x4R_rVt/sS4N2Gimv1pNwG_9/U-70hOzy1Jw4J7TG/xMMjDzXZA1Wg5rLC/Vi0plsoVaJmGtT78/g2isEH48dyMOLZDW/d8V75zvMql_dJXTZ/8Hyk-1HGTKoeVqmH/h45BTw.webp', checkout_url: 'https://shop.tallboy.us/products/tbj-journal-2' },
  { slug: 'tbj-got-something-to-say-2', title: 'TBJ Got Something To Say', price: '$27.00', image_url: 'https://imgproxy.fourthwall.dev/2DIMHv7ZBXpkplN16Se1NfzuvSL8acOBZ6jHRZU69nc/w:1920/sm:1/enc/8aomhqoYHRVToPGU/B1o_fdNxcFB6kjTn/BkHUFJ68Vt4EqT4i/Aw_N7o6cnEqjb4a8/2BR-IsHeg5iGVB9-/LQxEejsCFZQSd2aE/3yuN0_L-yy7t_H9Q/-9bEFJgKuW0-fGWS/bSHy2sbC5K6UfUW9/D7sLotv0Z20a7jPn/kWTC0QI3j6bleSg5/v3aN6s9LOp0Mv_IO/GiYHJjZiKaQ0HLfj/a7yXYdaZAiux1k4c/Bh5hJDNIRQ4.jpg', checkout_url: 'https://shop.tallboy.us/products/tbj-got-something-to-say-2' },
  { slug: 'standin-on-potty-onesie', title: "Standin' On Potty Onesie", price: '$21.99', image_url: 'https://imgproxy.fourthwall.dev/zQsvQgklpYwx1Tv5jlw09E3FS6bi5H3H34CDbEEWhZg/w:1920/sm:1/enc/CDrHPt4VflAycd8M/zijIzUimryJsQcEs/Y41FKYR1dLPv1VAw/GmxICGmvj5A6DGAr/8rJ0_pw0RetgeZjt/zuslH11mI5qJhei_/WtYcj0BDLrTqK0V4/5XClTCE9BkAWlSY_/nHx2EHa_p9s5Eu3e/ozsysnFUOiqwQ9PC/enD4sxvNsyFJwzE6/8uiiDZPAb82ZeynX/IeUUYIL6IPEY7K2a/mcnijSzDw_weqTjf/r7tqhFA63qM.jpg', checkout_url: 'https://shop.tallboy.us/products/standin-on-potty-onesie' }
];

// All known product slugs on shop.tallboy.us — used to drive a live re-scrape.
const TALL_BOY_SLUGS = TALL_BOY_PRODUCTS.map(p => p.slug);

const STORE_BASE = 'https://shop.tallboy.us';

module.exports = { TALL_BOY_PRODUCTS, TALL_BOY_SLUGS, STORE_BASE };
